"""new table  added

Revision ID: d4eb0c45357e
Revises: b7847cb629e7
Create Date: 2026-03-14 20:12:59.676574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4eb0c45357e'
down_revision: Union[str, Sequence[str], None] = 'b7847cb629e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('others',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_others_description'), 'others', ['description'], unique=False)
    op.create_index(op.f('ix_others_id'), 'others', ['id'], unique=False)
    op.create_index(op.f('ix_others_title'), 'others', ['title'], unique=False)
    op.drop_index(op.f('ix_notes_description'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_priority'), table_name='notes')
    op.drop_index(op.f('ix_notes_title'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_note_priority'), table_name='note')
    op.drop_column('note', 'completed')
    op.drop_column('note', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('note', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_note_priority'), 'note', ['priority'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('notes_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notes_pkey'))
    )
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    op.create_index(op.f('ix_notes_priority'), 'notes', ['priority'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_description'), 'notes', ['description'], unique=False)
    op.drop_index(op.f('ix_others_title'), table_name='others')
    op.drop_index(op.f('ix_others_id'), table_name='others')
    op.drop_index(op.f('ix_others_description'), table_name='others')
    op.drop_table('others')
    # ### end Alembic commands ###
