"""new table  added

Revision ID: f4292dbe20d8
Revises: d4eb0c45357e
Create Date: 2026-03-14 23:00:30.562537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4292dbe20d8'
down_revision: Union[str, Sequence[str], None] = 'd4eb0c45357e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_others_description'), table_name='others')
    op.drop_index(op.f('ix_others_id'), table_name='others')
    op.drop_index(op.f('ix_others_title'), table_name='others')
    op.drop_table('others')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('others',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('others_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('others_pkey'))
    )
    op.create_index(op.f('ix_others_title'), 'others', ['title'], unique=False)
    op.create_index(op.f('ix_others_id'), 'others', ['id'], unique=False)
    op.create_index(op.f('ix_others_description'), 'others', ['description'], unique=False)
    # ### end Alembic commands ###
